### ISSUE TITLE
Ruleset updates on every run

### ISSUE THREAD

**Issue by buric** [pulumi/pulumi-cloudflare#444]
### What happened?

Pulumi wants to update `cloudflare.Ruleset` on every execution, even though it shows no changes.
This behaviour started after we upgraded to v5, on v4 it worked correctly.

### Expected Behavior

Update `cloudflare.Ruleset` only if the definition of the resource was changed.

### Steps to reproduce

Add new `cloudflare.Ruleset` to the source code and run `pulumi up` to create the resource. Then run `pulumi up` and pulumi will try to update the resource.

### Output of `pulumi about`

CLI          
Version      3.75.0
Go Version   go1.20.6
Go Compiler  gc

Host     
OS       darwin
Version  13.2.1
Arch     arm64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by buric** [comment]
Update the provider to v5.6.0 today and same thing happens.

**Comment by buric** [comment]
Here is an example:
`
new cloudflare.Ruleset("transform_uri_rule_query", {
    description: "change the URI query to a new static query",
    kind: "zone",
    name: "transform rule for URI query parameter",
    phase: "http_request_transform",
    rules: [
        {
            action: "rewrite",
            actionParameters: {
                uri: {
                    query: {
                        value: "old=new_again",
                    },
                },
            },
            description: "URI transformation query example",
            enabled: true,
            expression: 'http.host eq "test"',
        },
    ],
    zoneId: zone.id,
});
`

**Comment by notdodo** [comment]
any update on this?

**Comment by mikhailshilkov** [comment]
I can repro this issue with this simple program:

```
import * as pulumi from "@pulumi/pulumi";
import * as cloudflare from "@pulumi/cloudflare";

const accountId = "<redacted>";

const zone = new cloudflare.Zone("my-zone", {
    zone: "ts-test-cloudflare-zone.com",
    accountId: accountId,
});

new cloudflare.Ruleset("transform_uri_rule_query", {
    description: "change the URI query to a new static query",
    kind: "zone",
    name: "transform rule for URI query parameter",
    phase: "http_request_transform",
    rules: [
        {
            action: "rewrite",
            actionParameters: {
                uri: {
                    query: {
                        value: "old=new_again",
                    },
                },
            },
            description: "URI transformation query example",
            enabled: true,
            expression: 'http.host eq "test"',
        },
    ],
    zoneId: zone.id,
});
```

On the second update, the diff shows an empty update with no changes in details.

In the logs, I see 

```
Provider[cloudflare, 0x14000fbea00].Diff(urn:pulumi:dev::other-ts::cloudflare:index/ruleset:Ruleset::transform_uri_rule_query,58cee299771345a3ac938176085003e6) success: changes=2 #replaces=[] #stables=[] delbefrepl=false, diffs=#[rules], detaileddiff=map[]
```

Interestingly, the problem does not reproduce on 5.0.0 version but starts happening on 5.1.0, which represents upstream update from 4.1.0 to 4.5.0. I don't have further ideas yet, we'll need to debug this.

cc @t0yv0 since this is another diff issue

**Comment by VitoSantos22** [comment]
Any news on this ?

**Comment by vavsab** [comment]
This [big recent PR in TF provider](https://github.com/cloudflare/terraform-provider-cloudflare/pull/2271) looks super suspicious.
Tested TF at 4.5.0 - they have no such a problem. It's something with a pulumi provider mapping to new TF model.

**Comment by t0yv0** [comment]
There is an unexpected diff between nil and empty list. Example path:

```
AttributeName("rules").ElementKeyInt(0).AttributeName("logging")
```

The root cause is fixed with https://github.com/pulumi/pulumi-terraform-bridge/pull/1616  and I'll try to propagate this fix here as soon as it's reviewed and we land it in the bridge. 

In addition https://github.com/pulumi/pulumi-terraform-bridge/issues/752 would be nice to complete here because `pulumi preview --diff` is not showing what it thinks is changing otherwise, which could have saved some time diagnosing the issue.

**Comment by gleb-jiji** [comment]
5.18.1 has fixed the issue for `http_request_transform` rulesets but I'm still seeing it with a `http_request_firewall_custom` ruleset. Any simple way to find the cause in this case?

**Comment by t0yv0** [comment]
> 5.18.1 has fixed the issue for http_request_transform rulesets but I'm still seeing it with a http_request_firewall_custom ruleset. Any simple way to find the cause in this case?

@gleb-jiji could you please file a new issue with repro? I'd love to have a look.
